### ISSUE TITLE
Mate menu "Super key shortcut"  makes impossible to use Super key for another shortcut

### ISSUE THREAD

**Issue by hiboudev** [linuxmint/mate#10] opened 2016-01-09 00:04 UTC
In most Linux desktops I used (like in Windows), I found the Super key used to open the main Menu, and the Super+E shortcut used to open file explorer. And in the case it wasn't configured by default, I was able to do it myself. (there is also Super+D to show the Desktop, Super+R to Run a command, etc)

In Mate, the menu can be opened with Super key, but if you try to add a shortcut (with the gui in control center) using the Super key (like Super+E), it won't work. You have to change the shortcut of the Menu to be a combination, like Super+W.

Please, make the Menu able to be opened with Super key only, without to prevent all other shortcuts using Super key.

**Comment by mrGrab** [comment] 2016-03-02 08:48
the same for me. Would like to use super (win) key for other shortcuts as well..

**Comment by monsta** [comment] 2016-04-11 11:21
Already reported at https://github.com/linuxmint/mintmenu/issues/98

**Comment by Zulgrib** [comment] 2016-10-02 02:31
Already reported and confirmed since 2014 and left abandoned.
Workaround given in comment works partly (you need to do the shortcut twice to make it take effect)

**Comment by clefebvre** [comment] 2017-05-13 19:03
This is fixed in 5.8.0 afaik.

**Closed by clefebvre** 2017-05-13 19:03 UTC
